// Code generated by "stringer -type=Field"; DO NOT EDIT.

package bits

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoOvervoltage-0]
	_ = x[NoOTPPrograming-1]
	_ = x[NoOTPReading-2]
	_ = x[Unused1-3]
	_ = x[WarrantyVoid-4]
	_ = x[Unused2-5]
	_ = x[NewStyleRev-6]
	_ = x[Memory-7]
	_ = x[Manufacturer-8]
	_ = x[Processor-9]
	_ = x[Model-10]
	_ = x[Revision-11]
	_ = x[NumTotal-12]
	_ = x[First-0]
}

const _Field_name = "NoOvervoltageNoOTPProgramingNoOTPReadingUnused1WarrantyVoidUnused2NewStyleRevMemoryManufacturerProcessorModelRevisionNumTotal"

var _Field_index = [...]uint8{0, 13, 28, 40, 47, 59, 66, 77, 83, 95, 104, 109, 117, 125}

func (i Field) String() string {
	if i >= Field(len(_Field_index)-1) {
		return "Field(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_name[_Field_index[i]:_Field_index[i+1]]
}
